from pydantic import BaseModel, Field
from typing import Annotated, Literal, Optional, List, Dict, Any
from operator import add

# Auto-instrument Pydantic schemas with Logfire if available
try:
    import logfire
    logfire.instrument_pydantic()
except Exception:
    pass


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the agent")
    user_question: str = Field(default="", description="The original question asked by the user")
    curated_ques: str = Field(default="", description="Curated user question")
    prompt_query_context: str = Field(default="", description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query: str = Field(default="", description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(default="", description="Comments regarding the safety of the generated SQL query")
    sql_query_execution_result: str = Field(default="", description="The result of executing the generated SQL query on the database")
    final_answer: str = Field(default="", description="The final answer generated by the agent based on the SQL query execution result and the curated question")
    retry_count: int = Field(default=0, description="Number of auto-repair retry attempts for SQL execution")
    error_trace: str = Field(default="", description="Error message from database execution if SQL failed")
    structured_data: Optional[List[Dict[str, Any]]] = Field(default=None, description="Structured query results for UI tables and charts")
    chart_spec: Optional[str] = Field(default=None, description="Plotly JSON specification or chart type for visualization")


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")


class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the ETL agent")
    output_file: Optional[str] = Field(default=None, description="File path of the created/transformed dataset")
    preview_data: Optional[List[Dict[str, Any]]] = Field(default=None, description="Top preview rows of the transformed dataset")


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the Data agent")
    route_response: str = Field(default="", description="The response from the router indicating whether to route to SQL or ETL operations")
    structured_data: Optional[List[Dict[str, Any]]] = Field(default=None, description="Structured table data passed from sub-agents to UI")
    chart_spec: Optional[str] = Field(default=None, description="Chart specification passed from sub-agents to UI")
    output_file: Optional[str] = Field(default=None, description="Exported file path passed from sub-agents")